import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="gradient-bg min-h-screen px-4 py-8">
      <div className="mx-auto max-w-2xl">
        {/* Back button */}
        <button
          onClick={() => navigate("/")}
          className="mb-8 flex items-center gap-1 text-sm text-muted-foreground transition-colors hover:text-foreground"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </button>

        {/* Content */}
        <article className="animate-fade-in-up space-y-6">
          <h1 className="text-glow-purple text-3xl font-bold tracking-tight">
            Terms of Service
          </h1>

          <p className="text-sm text-muted-foreground">
            Last updated: February 2026
          </p>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              1. Acceptance of Terms
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              By accessing and using Louuz, you agree to comply with these Terms of Service. 
              If you do not agree with any part of these terms, you must not use the platform. 
              Continued use of the service constitutes your acceptance of these terms and any future updates.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              2. Age Restriction
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              You must be at least <strong className="text-foreground">18 years old</strong> to use Louuz. 
              By using this service, you confirm that you meet this age requirement. 
              We are not responsible for the use of this platform by minors.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              3. User Conduct
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              By using Louuz, you agree NOT to:
            </p>
            <ul className="ml-4 list-disc space-y-1 text-sm text-muted-foreground">
              <li>Transmit any content that is illegal, offensive, threatening, or discriminatory.</li>
              <li>Engage in harassment, bullying, or intimidation of any kind.</li>
              <li>Share personal information of others without their consent.</li>
              <li>Use the platform for commercial purposes, spam, or advertising.</li>
              <li>Attempt to hack, disrupt, or access private data of other users.</li>
              <li>Violate the rights of others based on race, gender, religion, or orientation.</li>
            </ul>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              4. Privacy & Data
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Louuz does not store messages, usernames, or any personal data persistently. 
              All conversations are temporary and are not saved after you disconnect. 
              We do not share any user data with third parties. Your anonymity is our priority.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              5. Disclaimer of Warranties
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Louuz is provided on an "as is" basis, without warranties of any kind. 
              We are not responsible for content generated by other users, service uptime, 
              or any direct or indirect damages resulting from the use of the platform. 
              Use at your own risk.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold text-foreground">
              6. Modifications
            </h2>
            <p className="text-sm leading-relaxed text-muted-foreground">
              We reserve the right to modify these terms at any time. 
              Changes become effective immediately upon posting. 
              We recommend reviewing these terms periodically.
            </p>
          </section>

          {/* Back button */}
          <div className="pt-4">
            <Button
              onClick={() => navigate("/")}
              variant="outline"
              className="border-border text-foreground hover:bg-secondary"
            >
              <ArrowLeft className="mr-2 h-4 w-4" />
              Back to Home
            </Button>
          </div>
        </article>
      </div>
    </div>
  );
};

export default Terms;